// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Supabase: Use direct URL for migrations, pooler URL at runtime
    // Migrations: DIRECT_URL (port 5432) bypasses pgbouncer for DDL
    // Runtime: DATABASE_URL (port 6543) uses connection pooling
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
