import icon from './assets/icon.svg';

export const meta = {
  id: 'javascript',
  notionId: '5118e5a2-987a-4bf9-ac1f-c1c55c138b23',
  title: 'Javascript',
  '분류': [
    '언어',
  ],
  '언어로써 사용된 프로젝트': [
    'notion-desktop-app',
    '아이박스-주차',
    'smart-home-with-google-home',
    'youtogether',
    'dutchpay-웹',
    'midi-video-generator',
    'took',
    'arai',
    '비탈길-vitalgheal',
    '잔그림',
    '포문',
    'stella',
    'hana',
    'chain-post',
    'luna-coding',
    'sospitas',
    '디미고라이프',
    'canetis',
    'pubg-디스코드-봇',
    '산울림',
    'unipad',
    'eyevacs4',
    'hufs-스터디룸-예약-시스템',
  ],
  iconSlug: 'javascript',
  visible: true,
  '숙련도': '3. 상급',
  '관련 기술': [
    'nodejs',
    'discord-bot',
    'adobe-ae-script',
    'chrome-extention',
    'shell',
    'react',
    'react-native',
    'json',
    'electron',
    'next-js',
    'nest-js',
    'firebase',
    'i18next',
    'pwa',
    'vue',
    'svelte',
    'eslint',
    'npm',
    'axios',
    'datefns',
  ],
  '환경 및 기술': 'Javascript',
  icon,
};
