export const meta = {
  id: 'css3',
  notionId: 'a572a292-56a1-442b-a6c8-51c899c8e48d',
  title: 'CSS3',
  '분류': [
    '언어',
  ],
  '언어로써 사용된 프로젝트': [
    'mopl',
    'diy-drone',
    'notion-desktop-app',
    '아이박스-주차',
    'smart-home-with-google-home',
    'youtogether',
    'dutchpay-웹',
    'midi-video-generator',
    'took',
    'arai',
    '비탈길-vitalgheal',
    '잔그림',
    '포문',
    'stella',
    'chain-post',
    'luna-coding',
    'sospitas',
    '디미고라이프',
    'canetis',
    '산울림',
  ],
  iconSlug: 'css3',
  visible: true,
  '숙련도': '2. 중급',
  '관련 기술': [
    'html',
    'css3',
    'tailwind',
    'pwa',
  ],
  '환경 및 기술': 'CSS3',
};
