import icon from './assets/icon.png';

export const meta = {
  id: 'eyevacs4',
  notionId: '4b1c905e-56cf-4bc8-915d-c768337edf4e',
  title: 'Eyevacs4',
  Youtube: 'https://www.youtube.com/watch?v=bOmNnjNK3X8',
  '맡은 업무': [
    '개발',
  ],
  '프로그래밍 언어': [
    'javascript',
    'typescript',
  ],
  '중요도': '높음',
  '주요 기술': [
    'github',
    'prometheus',
    'aws-rds',
    'reactquery',
    'aws-ecs',
    'docker',
    'postgres',
    'i18next',
    'linear-app',
    'mongodb',
    'nodejs',
    'firebase',
    'react',
    'haproxy',
    'grafana',
    'redis',
    'react-native',
    'aws-ec2',
    'aws-s3',
    'prisma',
    'nest-js',
    'google-admob',
    'figma',
    'git',
    'github-actions',
  ],
  visible: true,
  URL: 'https://www.eyevacs.com',
  '설명': '아파트 통합 관리 솔루션',
  '날짜': '2023-08-01',
  '분류': [
    '회사',
  ],
  '갤러리에서 보기': false,
  '이름': 'Eyevacs4',
  icon,
};
