import icon from './assets/icon.svg';
import type { SkillMeta } from '@/content/types';

export const meta: SkillMeta = {
  id: 'html',
  notionId: '03904233-518c-42f4-a179-0711a29d5dca',
  title: 'HTML',
  '분류': [
    '언어',
  ],
  '언어로써 사용된 프로젝트': [
    'mopl',
    'diy-drone',
    'notion-desktop-app',
    '아이박스-주차',
    'smart-home-with-google-home',
    'youtogether',
    'dutchpay-웹',
    'midi-video-generator',
    'took',
    'arai',
    '비탈길-vitalgheal',
    '잔그림',
    '포문',
    'stella',
    'chain-post',
    'luna-coding',
    'sospitas',
    '디미고라이프',
    'canetis',
    '산울림',
  ],
  iconSlug: 'html5',
  visible: true,
  '숙련도': '3. 상급',
  '기술로써 사용된 프로젝트': [
    'youtogether',
    'diy-drone',
    'mopl',
  ],
  '관련 기술': [
    'react',
    'chrome-extention',
    'css3',
    'svg',
    'mui',
    'pwa',
    'svelte',
  ],
  '환경 및 기술': 'HTML',
  icon,
};
